// 每项技能一个图标。
//
// 用 lucide 的线图标，不用生成的图片：它们是矢量、跟着 currentColor 走，
// 所以"点亮"可以是同一个图标换个颜色加一圈光晕，而不是两张图片。
// 新增技能时这里漏了会被 skill-icons.test.ts 挡下来。

import {
  AlarmClock,
  AlignLeft,
  Anchor,
  Archive,
  ArrowUpRight,
  BadgeCheck,
  Banknote,
  Bed,
  Blocks,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Bug,
  Calculator,
  CalendarDays,
  ChartNoAxesColumn,
  ClipboardCheck,
  Coins,
  Compass,
  Copy,
  Crosshair,
  Dumbbell,
  Ear,
  Eye,
  FileSearch,
  Fingerprint,
  Flame,
  Gauge,
  GitBranch,
  Handshake,
  HelpCircle,
  HeartPulse,
  Highlighter,
  Keyboard,
  Landmark,
  Languages,
  Layers,
  Library,
  LifeBuoy,
  Lightbulb,
  Magnet,
  Megaphone,
  MessageCircleQuestion,
  Mic,
  Microscope,
  Milestone,
  Network,
  Notebook,
  PackageCheck,
  PenLine,
  PiggyBank,
  Presentation,
  Radar,
  Radio,
  RefreshCw,
  Repeat,
  Route,
  Ruler,
  Save,
  Scale,
  ScanEye,
  Scissors,
  Search,
  Send,
  ShieldOff,
  ShoppingCart,
  Signature,
  Siren,
  Sparkles,
  Split,
  SquareStack,
  Table,
  Tag,
  Target,
  Telescope,
  TrendingUp,
  Truck,
  UserRoundCheck,
  UserRoundSearch,
  Users,
  Wand,
  Waypoints,
  WifiOff,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const SKILL_ICONS: Record<string, LucideIcon> = {
  // 元件
  record: Notebook,
  search: Search,
  skim: Gauge,
  summarize: AlignLeft,
  askbasic: MessageCircleQuestion,
  paraphrase: Repeat,
  remembernames: UserRoundCheck,
  toolcraft: Keyboard,
  arithmetic: Calculator,
  spreadsheet: Table,
  formatting: Highlighter,
  punctual: AlarmClock,
  statusreport: Megaphone,
  backup: Save,
  shield: ShieldOff,
  trace: Waypoints,
  listening: Ear,
  observing: Eye,
  sleepcraft: Bed,

  // 回路
  asking: Mic,
  experiment: Microscope,
  probing: FileSearch,
  profiling: UserRoundSearch,
  synthesis: Layers,
  writing: PenLine,
  coldopen: Radio,
  jpbiz: Languages,
  explaining: Lightbulb,
  headline: Tag,
  rhetoric: Wand,
  structure: SquareStack,
  coding: Keyboard,
  debugging: Bug,
  testing: ClipboardCheck,
  finance: Coins,
  support: LifeBuoy,
  procurement: ShoppingCart,
  retro: RefreshCw,
  forecasting: Target,
  scheduling: CalendarDays,
  training: Dumbbell,
  recovery: HeartPulse,
  learning: Library,
  focuscraft: Crosshair,
  askinghelp: LifeBuoy,
  feedback: Send,
  takingheat: Anchor,
  introducing: BadgeCheck,
  keepingup: Magnet,
  silence: ShieldOff,
  spotfake: ScanEye,

  // 模组
  analysis: ChartNoAxesColumn,
  research: Telescope,
  finstmt: Landmark,
  recon: Radar,
  presenting: Presentation,
  negotiating: Scale,
  persuading: Megaphone,
  narrative: Route,
  teachingwrite: Milestone,
  productdesign: Scissors,
  prototyping: Blocks,
  aiorchestration: Network,
  automation: Wrench,
  architecture: GitBranch,
  performance: Gauge,
  dataplumb: Waypoints,
  pricing: Tag,
  hiring: Users,
  delegating: Handshake,
  processdesign: Ruler,
  partnering: Handshake,
  cashflow: PiggyBank,
  uniteconomics: Calculator,
  channel: Compass,
  metacog: Brain,
  trustbuilding: BadgeCheck,
  conflict: Scale,
  mentoring: Users,
  mediating: Handshake,
  interview: Mic,
  interrogate: ScanEye,
  fleet: Boxes,
  judgepeople: UserRoundSearch,
  refer: Waypoints,
  redundancy: LifeBuoy,
  ship: Truck,
  oncall: Siren,

  // 内核
  systemcraft: Network,
  duediligence: FileSearch,
  acceptance: ClipboardCheck,
  framing: HelpCircle,
  decompose: Split,
  orgdesign: Building2,
  managingup: ArrowUpRight,
  revenue: Banknote,
  crisis: Flame,
  integration: Blocks,
  transcode: Languages,
  clone: Copy,
  offline: WifiOff,
  humanproof: Fingerprint,
  compounding: TrendingUp,
  curation: Archive,

  // 印记
  judgement: Compass,
  requestion: RefreshCw,
  handover: PackageCheck,
  settingtone: Signature,
  selfrunning: Repeat,
  ownership: Signature,
  dealmaking: Briefcase,
  unattended: Radio,
  gravity: Magnet,
  custody: Boxes,
  retention: Library,
};

export const FALLBACK_SKILL_ICON: LucideIcon = Sparkles;

export function iconFor(key: string): LucideIcon {
  return SKILL_ICONS[key] ?? FALLBACK_SKILL_ICON;
}
